# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnVAW5fYi6XZ2psT-QNICCkLFhfUu-D7
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

df = pd.read_csv('/content/sample_data/winequality-red.csv', sep=';')

df.info()

df.head()

df.describe()

tc = 'quality'
y = df[tc]
X = df.drop(columns=[tc])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
r2

mse = mean_squared_error(y_test, y_pred)
mse

plt.scatter(y_test, y_pred)
plt.show()

import joblib

joblib.dump(model, "model.pkl")

